=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/testreport.dtd
<!--                                                                        -->
<!--                                                                        -->
<!--  This file is part of the Frama-C plug-in 'PathCrawler' (pc).          -->
<!--                                                                        -->
<!--  Copyright (C) 2007-2023                                               -->
<!--    CEA (Commissariat à l'énergie atomique et aux énergies              -->
<!--         alternatives)                                                  -->
<!--                                                                        -->
<!--  All rights reserved.                                                  -->
<!--  Contact CEA LIST for licensing.                                       -->
<!--                                                                        -->
<!--                                                                        -->

<!-- Test Report: contains 
  Test Session Data, Duration;
  test session statistics,
  the Unreachable and Uncovered Branches by this test session (optional)
  the Uncovered Labels by this test session (optional)
 -->
<!ELEMENT TestReport (SessionData,Dur,TotalPrefixNum,CoveredNum,TimeoutNum,InfeasibleNum,AssumeViolatedNum,IterLimitViolatedNum,PCBugNum,UntreatedNum,SubsumedNum,SuccessNum,UnknownNum,FailureNum,AssertViolatedNum,CrashedNum,HungNum,SegFaultNum,UninitVarNum,BugOracleNum,MaybeSuccessNum,MaybeUnknownNum,MaybeFailureNum,TermStatus?,UnreachableBranches?,UncoveredBranches?,UncoveredLabels?)>

<!-- Test Session Data: contains
  Function Name, Strategy and time When this generation session started -->
<!ELEMENT SessionData (FunName,Strategy,When,Version,TestReportFile,TestSessionFile)>
<!ELEMENT FunName (#PCDATA)>
<!-- Strategy: contains 3 required attributes and optional text in body 
(function name in case of func scope) -->
<!ELEMENT Strategy (#PCDATA)>
<!ATTLIST Strategy Coverage CDATA #REQUIRED>
<!ATTLIST Strategy IterLimit CDATA #REQUIRED>
<!ATTLIST Strategy RecurLimit CDATA #REQUIRED>
<!ATTLIST Strategy SuffixLengthLimit CDATA #REQUIRED>
<!ELEMENT When (#PCDATA)>
<!ELEMENT Version (#PCDATA)>

<!ELEMENT Dur (#PCDATA)>

<!-- Number of treated path prefixes: Total and for each status -->
<!ELEMENT TotalPrefixNum (#PCDATA)>
<!ELEMENT CoveredNum (#PCDATA)>
<!ELEMENT TimeoutNum (#PCDATA)>
<!ELEMENT InfeasibleNum (#PCDATA)>
<!ELEMENT AssumeViolatedNum (#PCDATA)>
<!ELEMENT IterLimitViolatedNum (#PCDATA)>
<!ELEMENT PCBugNum (#PCDATA)>
<!ELEMENT UntreatedNum (#PCDATA)>
<!ELEMENT SubsumedNum (#PCDATA)>
<!ELEMENT UninitVarNum (#PCDATA)>

<!-- Number of test cases with each verdict -->
<!ELEMENT SuccessNum (#PCDATA)>
<!ELEMENT UnknownNum (#PCDATA)>
<!ELEMENT FailureNum (#PCDATA)>
<!ELEMENT AssertViolatedNum (#PCDATA)>
<!ELEMENT InterruptNum (#PCDATA)>
<!ELEMENT CrashedNum (#PCDATA)>
<!ELEMENT HungNum (#PCDATA)>
<!ELEMENT BugOracleNum (#PCDATA)>
<!ELEMENT MaybeSuccessNum (#PCDATA)>
<!ELEMENT MaybeUnknownNum (#PCDATA)>
<!ELEMENT MaybeFailureNum (#PCDATA)>

<!-- Separate XML file containing test session file -->
<!ELEMENT TestSessionFile (#PCDATA)>

<!-- Separate XML file containing test report file -->
<!ELEMENT TestReportFile (#PCDATA)>

<!-- Termination status -->
<!ELEMENT TermStatus (#PCDATA)>
<!ATTLIST TermStatus Type CDATA #REQUIRED>

<!-- UnreachableBranches: Sequence of positive (P) and negative (N) conditions denoted 
     by line and node numbers and source file name -->
<!ELEMENT UnreachableBranches ((P|N)*)>
<!ELEMENT P (#PCDATA)>
<!ATTLIST P SrcFile CDATA #REQUIRED>
<!ATTLIST P BlocID CDATA #REQUIRED>
<!ELEMENT N (#PCDATA)>
<!ATTLIST N SrcFile CDATA #REQUIRED>
<!ATTLIST N BlocID CDATA #REQUIRED>

<!-- UncoveredBranches: Sequence of positive (P) and negative (N) conditions denoted 
     by line and node numbers and source file name -->
<!ELEMENT UncoveredBranches ((P|N)*)>

<!-- UncoveredLabels: Sequence of elements LID each of them defines an uncovered label identifier -->
<!ELEMENT UncoveredLabels (LID*)>
<!ELEMENT LID (#PCDATA)>

=== ggranberry/acslyst/examples/TriType/testcases_TriType/Tritype/xml/testreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestReport SYSTEM "testreport.dtd">
<?xml-stylesheet href="testreport2html.xsl" type="text/xsl"?>
<TestReport>
 <SessionData>
  <FunName>Tritype</FunName>
  <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
  <When>Tue Jun 27 15:07:51 2023</When>
  <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
  <TestReportFile>testreport.xml</TestReportFile>
  <TestSessionFile>testsession.xml</TestSessionFile>
 </SessionData>
 <Dur>1</Dur>
 <TotalPrefixNum>18</TotalPrefixNum>
 <CoveredNum>9</CoveredNum>
 <TimeoutNum>0</TimeoutNum>
 <InfeasibleNum>7</InfeasibleNum>
 <AssumeViolatedNum>0</AssumeViolatedNum>
 <IterLimitViolatedNum>1</IterLimitViolatedNum>
 <PCBugNum>0</PCBugNum>
 <UntreatedNum>0</UntreatedNum>
 <SubsumedNum>0</SubsumedNum>
 <SuccessNum>0</SuccessNum>
 <UnknownNum>9</UnknownNum>
 <FailureNum>0</FailureNum>
 <AssertViolatedNum>0</AssertViolatedNum>
 <CrashedNum>0</CrashedNum>
 <HungNum>0</HungNum>
 <InterruptNum>0</InterruptNum>
 <UninitVarNum>0</UninitVarNum>
 <BugOracleNum>0</BugOracleNum>
 <MaybeSuccessNum>0</MaybeSuccessNum>
 <MaybeUnknownNum>0</MaybeUnknownNum>
 <MaybeFailureNum>0</MaybeFailureNum>
 <TermStatus Type="normally">
 </TermStatus>
 <UncoveredBranches>
  <P BlocID="286" SrcFile="TriType.c">17</P>
 </UncoveredBranches>
 <UnreachableBranches />
</TestReport>

=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/testreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestReport SYSTEM "testreport.dtd">
<?xml-stylesheet href="testreport2html.xsl" type="text/xsl"?>
<TestReport>
 <SessionData>
  <FunName>testme</FunName>
  <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
  <When>Mon Nov 20 16:07:18 2023</When>
  <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
  <TestReportFile>testreport.xml</TestReportFile>
  <TestSessionFile>testsession.xml</TestSessionFile>
 </SessionData>
 <Dur>0</Dur>
 <TotalPrefixNum>2</TotalPrefixNum>
 <CoveredNum>0</CoveredNum>
 <TimeoutNum>0</TimeoutNum>
 <InfeasibleNum>2</InfeasibleNum>
 <AssumeViolatedNum>0</AssumeViolatedNum>
 <IterLimitViolatedNum>0</IterLimitViolatedNum>
 <PCBugNum>0</PCBugNum>
 <UntreatedNum>0</UntreatedNum>
 <SubsumedNum>0</SubsumedNum>
 <SuccessNum>0</SuccessNum>
 <UnknownNum>0</UnknownNum>
 <FailureNum>0</FailureNum>
 <AssertViolatedNum>0</AssertViolatedNum>
 <CrashedNum>0</CrashedNum>
 <HungNum>0</HungNum>
 <InterruptNum>0</InterruptNum>
 <UninitVarNum>0</UninitVarNum>
 <BugOracleNum>0</BugOracleNum>
 <MaybeSuccessNum>0</MaybeSuccessNum>
 <MaybeUnknownNum>0</MaybeUnknownNum>
 <MaybeFailureNum>0</MaybeFailureNum>
 <TermStatus Type="unknown">
 </TermStatus>
 <UncoveredBranches>
  <P BlocID="1003" SrcFile="/work/pathcrawler/troubleshoot.c">81a</P>
  <N BlocID="1003" SrcFile="/work/pathcrawler/troubleshoot.c">81a</N>
  <P BlocID="805" SrcFile="/work/pathcrawler/pathcrawler_tests/EchoBranches/system.h">55</P>
  <N BlocID="805" SrcFile="/work/pathcrawler/pathcrawler_tests/EchoBranches/system.h">55</N>
  <P BlocID="1007" SrcFile="/work/pathcrawler/troubleshoot.c">81b</P>
  <N BlocID="1007" SrcFile="/work/pathcrawler/troubleshoot.c">81b</N>
  <P BlocID="800" SrcFile="/work/pathcrawler/pathcrawler_tests/EchoBranches/system.h">54</P>
  <N BlocID="800" SrcFile="/work/pathcrawler/pathcrawler_tests/EchoBranches/system.h">54</N>
  <N BlocID="980" SrcFile="/work/pathcrawler/troubleshoot.c">61</N>
  <P BlocID="991" SrcFile="/work/pathcrawler/troubleshoot.c">62c</P>
  <N BlocID="991" SrcFile="/work/pathcrawler/troubleshoot.c">62c</N>
  <P BlocID="984" SrcFile="/work/pathcrawler/troubleshoot.c">62a</P>
 </UncoveredBranches>
 <UnreachableBranches />
</TestReport>
