=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/testsession.dtd
<!--                                                                        -->
<!--                                                                        -->
<!--  This file is part of the Frama-C plug-in 'PathCrawler' (pc).          -->
<!--                                                                        -->
<!--  Copyright (C) 2007-2023                                               -->
<!--    CEA (Commissariat à l'énergie atomique et aux énergies              -->
<!--         alternatives)                                                  -->
<!--                                                                        -->
<!--  All rights reserved.                                                  -->
<!--  Contact CEA LIST for licensing.                                       -->
<!--                                                                        -->
<!--                                                                        -->

<!-- Test Session: contains 
  Test Session Data and PrefixData for each considered path prefix -->
<!ELEMENT TestSession (SessionData,PrefixData*)>

<!-- Test Session Data: contains
  Function Name, Strategy and time When this generation session started -->
<!ELEMENT SessionData (FunName,Strategy,When,Version,TestReportFile,TestSessionFile)>
<!ELEMENT FunName (#PCDATA)>
<!-- Strategy: contains 3 required attributes and optional text in body 
(function name in case of func scope) -->
<!ELEMENT Strategy (#PCDATA)>
<!ATTLIST Strategy Coverage CDATA #REQUIRED>
<!ATTLIST Strategy IterLimit CDATA #REQUIRED>
<!ATTLIST Strategy RecurLimit CDATA #REQUIRED>
<!ATTLIST Strategy SuffixLengthLimit CDATA #REQUIRED>
<!ELEMENT When (#PCDATA)>
<!ELEMENT Version (#PCDATA)>

<!ELEMENT PrefixData (Time,Dur,Prefix,Suffix?,PrefixStatus,TestCaseFile?,Verdict?)>
<!-- Prefix Number: prefixed by a 'P_'-->
<!ATTLIST PrefixData PrefixID ID #REQUIRED>
<!-- Test Case Number: prefixed by a 'TC_', unique for this session-->
<!ATTLIST PrefixData TestCaseID CDATA #IMPLIED>

<!-- ATTN: consistency with io.pl -->
<!ELEMENT PrefixStatus (#PCDATA)>
<!ATTLIST PrefixStatus Status (covered|timeout|infeasible|assume_violated|iteration_limit_violated|no_extra_coverage|PC_bug|untreated|subsumed) #REQUIRED>

<!ELEMENT Time (#PCDATA)>
<!ELEMENT Dur (#PCDATA)>

<!-- Path: Sequence of positive (P) and negative (N) conditions denoted 
  by line numbers with optional attributes containing source file name 
  for the first node or when different from the previous node,
  and Label Indentifier (LID) when the condition comes from a label -->
<!ELEMENT Prefix ((P|N)*)>
<!ELEMENT Suffix ((P|N)*)>
<!ELEMENT P (#PCDATA)>
<!ATTLIST P SrcFile CDATA #IMPLIED>
<!ATTLIST P BlocID CDATA #IMPLIED>
<!ATTLIST P LID CDATA #IMPLIED>
<!ELEMENT N (#PCDATA)>
<!ATTLIST N SrcFile CDATA #IMPLIED>
<!ATTLIST N BlocID CDATA #IMPLIED>
<!ATTLIST N LID CDATA #IMPLIED>

<!-- Separate XML file containing test case data -->
<!ELEMENT TestCaseFile (#PCDATA)>

<!-- Separate XML file containing test session file -->
<!ELEMENT TestSessionFile (#PCDATA)>

<!-- Separate XML file containing test report file -->
<!ELEMENT TestReportFile (#PCDATA)>

<!-- Verdict: contains one required attribute and optional text in body 
(line number for assert_violated, message for failure, etc.) -->
<!-- ATTN: consistency with io.pl -->
<!ELEMENT Verdict (#PCDATA)>
<!ATTLIST Verdict Type (success|unknown|failure|assert_violated|assert_violated_in_oracle|crashed|hung|interrupt|bug_oracle|maybe_success|maybe_unknown|maybe_failure|invalid_memory_access|deref_null_pointer|use_after_free|div_by_0|uninit_var|invalid_arg|error|no_extra_coverage|none) #REQUIRED>

<!-- PathPredicate: List of constraints of the path predicate
  with optional attributes containing source file name (SrcFile)
  for the first node or when different from the previous node, line (L)
  and label indentifier (LID) when the condition comes from a label -->
<!ELEMENT PathPredicate (Ctr*)>
<!ELEMENT Ctr (#PCDATA)>
<!ATTLIST Ctr L CDATA #IMPLIED>
<!ATTLIST Ctr SrcFile CDATA #IMPLIED>
<!ATTLIST Ctr LID CDATA #IMPLIED>

=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/testsession.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestSession SYSTEM "testsession.dtd">
<?xml-stylesheet href="testsession2html_table.xsl" type="text/xsl"?>
<TestSession>

<SessionData>
 <FunName>testme</FunName>
 <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
 <When>Mon Nov 20 16:07:18 2023</When>
 <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
 <TestReportFile>testreport.xml</TestReportFile>
 <TestSessionFile>testsession.xml</TestSessionFile>
</SessionData>
<PrefixData TestCaseID="TC_1" PrefixID="P_4">
 <Time>Mon Nov 20 16:07:18 2023</Time>
 <Dur>0</Dur>
 <Prefix>
  <P BlocID="980" SrcFile="/work/pathcrawler/troubleshoot.c">61</P>
  <N BlocID="984">62a</N>
  <P BlocID="987">62b</P>
 </Prefix>
 <Suffix />
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_1.xml</TestCaseFile>
 <Verdict Type="interrupt">The tested function was interrupted (signal 11 (SIGSEGV - Invalid memory reference)) after executing the positive branch of the 2nd condition at line number 62 of file /work/pathcrawler/troubleshoot.c.
[pc] Please check your test context.
</Verdict>
</PrefixData>
</TestSession>

=== ggranberry/acslyst/examples/TriType/testcases_TriType/Tritype/xml/testsession.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestSession SYSTEM "testsession.dtd">
<?xml-stylesheet href="testsession2html_table.xsl" type="text/xsl"?>
<TestSession>

<SessionData>
 <FunName>Tritype</FunName>
 <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
 <When>Tue Jun 27 15:07:51 2023</When>
 <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
 <TestReportFile>testreport.xml</TestReportFile>
 <TestSessionFile>testsession.xml</TestSessionFile>
</SessionData>
<PrefixData TestCaseID="TC_1" PrefixID="P_2">
 <Time>Tue Jun 27 15:07:51 2023</Time>
 <Dur>0</Dur>
 <Prefix>
  <P BlocID="243" SrcFile="TriType.c">10a</P>
 </Prefix>
 <Suffix />
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_1.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_2" PrefixID="P_3">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <P BlocID="248">10b</P>
 </Prefix>
 <Suffix />
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_2.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_3" PrefixID="P_4">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <P BlocID="251">10c</P>
 </Prefix>
 <Suffix />
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_3.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_4" PrefixID="P_8">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
  <N BlocID="262">12b</N>
  <N BlocID="265">12c</N>
  <N BlocID="271">14</N>
 </Prefix>
 <Suffix>
  <P BlocID="276" SrcFile="TriType.c">15</P>
  <N BlocID="281">16</N>
  <N BlocID="286">17</N>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_4.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_5" PrefixID="P_12">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
  <N BlocID="262">12b</N>
  <N BlocID="265">12c</N>
  <N BlocID="271">14</N>
  <N BlocID="276">15</N>
  <P BlocID="281">16</P>
 </Prefix>
 <Suffix>
  <N BlocID="286" SrcFile="TriType.c">17</N>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_5.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_6" PrefixID="P_7">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
  <N BlocID="262">12b</N>
  <N BlocID="265">12c</N>
 </Prefix>
 <Suffix>
  <P BlocID="271" SrcFile="TriType.c">14</P>
  <N BlocID="276">15</N>
  <N BlocID="281">16</N>
  <N BlocID="286">17</N>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_6.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_7" PrefixID="P_6">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
  <N BlocID="262">12b</N>
 </Prefix>
 <Suffix>
  <P BlocID="265" SrcFile="TriType.c">12c</P>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_7.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_8" PrefixID="P_5">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
 </Prefix>
 <Suffix>
  <P BlocID="262" SrcFile="TriType.c">12b</P>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_8.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
<PrefixData TestCaseID="TC_9" PrefixID="P_1">
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Prefix />
 <Suffix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <P BlocID="257">12a</P>
 </Suffix>
 <PrefixStatus Status="covered" />
 <TestCaseFile>TC_9.xml</TestCaseFile>
 <Verdict Type="unknown" />
</PrefixData>
</TestSession>
