=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/testcase.dtd
<!--                                                                        -->
<!--                                                                        -->
<!--  This file is part of the Frama-C plug-in 'PathCrawler' (pc).          -->
<!--                                                                        -->
<!--  Copyright (C) 2007-2023                                               -->
<!--    CEA (Commissariat à l'énergie atomique et aux énergies              -->
<!--         alternatives)                                                  -->
<!--                                                                        -->
<!--  All rights reserved.                                                  -->
<!--  Contact CEA LIST for licensing.                                       -->
<!--                                                                        -->
<!--                                                                        -->

<!-- One Test Case: contains 
  Test Session Data, 
  Time when generation of this test case started,
  Duration of generation of this test case,
  Inputs data, oracle's Verdict, complete Path, concrete Outputs, 
  symbolic outputs,
  the PathPredicate,
  the Covered Labels by this TC (optional)-->
<!ELEMENT TestCase (SessionData,Time,Dur,Inputs,Verdict,Prefix,Suffix,Outputs,SymOutputs,PathPredicate,CoveredLabels?)>

<!-- Test Case Number: prefixed by a 'TC_', unique for this session-->
<!ATTLIST TestCase TestCaseID ID #REQUIRED>
<!ATTLIST TestCase PrevTestCaseID CDATA #IMPLIED>
<!ATTLIST TestCase NextTestCaseID CDATA #REQUIRED>
<!-- Prefix Number: prefixed by a 'P_'-->
<!ATTLIST TestCase PrefixID CDATA #REQUIRED>

<!-- Test Session Data: contains
  Function Name, Strategy and time When this generation session started -->
<!ELEMENT SessionData (FunName,Strategy,When,Version,TestReportFile,TestSessionFile)>
<!ELEMENT FunName (#PCDATA)>
<!-- Strategy: contains 4 required attributes and optional text in body 
(function name in case of func scope) -->
<!ELEMENT Strategy (#PCDATA)>
<!ATTLIST Strategy Coverage CDATA #REQUIRED>
<!ATTLIST Strategy IterLimit CDATA #REQUIRED>
<!ATTLIST Strategy RecurLimit CDATA #REQUIRED>
<!ATTLIST Strategy SuffixLengthLimit CDATA #REQUIRED>
<!ELEMENT When (#PCDATA)>
<!ELEMENT Version (#PCDATA)>

<!ELEMENT Time (#PCDATA)>
<!ELEMENT Dur (#PCDATA)>

<!-- Inputs: contains Array Dimensions and Variable Values, with 
Array or Variable Name and the value Num -->
<!ELEMENT Inputs (ArDim*,VVal*)>
<!ELEMENT ArDim (VName,Val)>
<!ELEMENT VVal (VName,Val)>
<!ELEMENT VName (#PCDATA)>
<!ELEMENT Val (#PCDATA)>

<!-- Verdict: contains one required attribute and optional text in body 
(line number for assert_violated, message for failure, etc.) -->
<!-- ATTN: consistency with io.pl -->
<!ELEMENT Verdict (#PCDATA)>
<!ATTLIST Verdict Type (success|unknown|failure|assert_violated|assert_violated_in_oracle|crashed|hung|interrupt|bug_oracle|maybe_success|maybe_unknown|maybe_failure|invalid_memory_access|div_by_0|deref_null_pointer|use_after_free|uninit_var|invalid_arg|error|no_extra_coverage|none) #REQUIRED>

<!-- Path: Sequence of positive (P) and negative (N) conditions denoted 
  by line numbers with optional attributes containing source file name (SrcFile)
  for the first node or when different from the previous node,
  and label indentifier (LID) when the condition comes from a label -->
<!ELEMENT Prefix ((P|N)*)>
<!ELEMENT Suffix ((P|N)*)>
<!ELEMENT P (#PCDATA)>
<!ATTLIST P SrcFile CDATA #IMPLIED>
<!ATTLIST P BlocID CDATA #IMPLIED>
<!ATTLIST P LID CDATA #IMPLIED>
<!ELEMENT N (#PCDATA)>
<!ATTLIST N SrcFile CDATA #IMPLIED>
<!ATTLIST N BlocID CDATA #IMPLIED>
<!ATTLIST N LID CDATA #IMPLIED>

<!-- Outputs: List of concrete outputs -->
<!ELEMENT Outputs (Output*)>
<!ELEMENT Output (VName,Val)>

<!-- SymOutputs: List of symbolic outputs -->
<!ELEMENT SymOutputs (SymOutput*)>
<!ELEMENT SymOutput (VName,Val)>

<!-- PathPredicate: List of constraints of the path predicate
  with optional attributes containing source file name (SrcFile)
  for the first node or when different from the previous node, line (L)
  and label indentifier (LID) when the condition comes from a label -->
<!ELEMENT PathPredicate (Ctr*)>
<!ELEMENT Ctr (#PCDATA)>
<!ATTLIST Ctr L CDATA #IMPLIED>
<!ATTLIST Ctr SrcFile CDATA #IMPLIED>
<!ATTLIST Ctr LID CDATA #IMPLIED>

<!-- Separate XML file containing test session file -->
<!ELEMENT TestSessionFile (#PCDATA)>

<!-- Separate XML file containing test report file -->
<!ELEMENT TestReportFile (#PCDATA)>

<!-- CoveredLabels: Sequence of elements LID each of them defines a covered label identifier -->
<!ELEMENT CoveredLabels (LID*)>
<!ELEMENT LID (#PCDATA)>

=== ggranberry/acslyst/examples/TriType/testcases_TriType/Tritype/xml/TC_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestCase SYSTEM "testcase.dtd">
<?xml-stylesheet href="testcase2html.xsl" type="text/xsl"?>
<TestCase TestCaseID="TC_2" PrevTestCaseID="TC_1" NextTestCaseID="TC_3" PrefixID="P_3">
 <SessionData>
  <FunName>Tritype</FunName>
  <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
  <When>Tue Jun 27 15:07:51 2023</When>
  <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
  <TestReportFile>testreport.xml</TestReportFile>
  <TestSessionFile>testsession.xml</TestSessionFile>
 </SessionData>
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Inputs>
  <VVal>
   <VName>i</VName>
   <Val>0</Val>
  </VVal>
  <VVal>
   <VName>j</VName>
   <Val>-1.7976931348623157e+308</Val>
  </VVal>
  <VVal>
   <VName>k</VName>
   <Val>0</Val>
  </VVal>
 </Inputs>
 <Verdict Type="unknown" />
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <P BlocID="248">10b</P>
 </Prefix>
 <Suffix />
 <Outputs>
  <Output>
   <VName>return value</VName>
   <Val>3</Val>
  </Output>
 </Outputs>
 <SymOutputs>
  <SymOutput>
   <VName>return value</VName>
   <Val>3</Val>
  </SymOutput>
 </SymOutputs>
 <PathPredicate>
  <Ctr>i&gt;=0</Ctr>
  <Ctr>j&lt;0</Ctr>
 </PathPredicate>
</TestCase>

=== ggranberry/acslyst/testcases_troubleshoot/testme/xml/TC_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestCase SYSTEM "testcase.dtd">
<?xml-stylesheet href="testcase2html.xsl" type="text/xsl"?>
<TestCase TestCaseID="TC_1" NextTestCaseID="TC_2" PrefixID="P_4">
 <SessionData>
  <FunName>testme</FunName>
  <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
  <When>Mon Nov 20 16:07:18 2023</When>
  <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
  <TestReportFile>testreport.xml</TestReportFile>
  <TestSessionFile>testsession.xml</TestSessionFile>
 </SessionData>
 <Time>Mon Nov 20 16:07:18 2023</Time>
 <Dur>0</Dur>
 <Inputs>
  <ArDim>
   <VName>argv</VName>
   <Val>0</Val>
  </ArDim>
  <VVal>
   <VName>argc</VName>
   <Val>1814420628</Val>
  </VVal>
 </Inputs>
 <Verdict Type="interrupt">The tested function was interrupted (signal 11 (SIGSEGV - Invalid memory reference)) after executing the positive branch of the 2nd condition at line number 62 of file /work/pathcrawler/troubleshoot.c.
[pc] Please check your test context.
</Verdict>
 <Prefix>
  <P BlocID="980" SrcFile="/work/pathcrawler/troubleshoot.c">61</P>
  <N BlocID="984">62a</N>
  <P BlocID="987">62b</P>
 </Prefix>
 <Suffix />
 <Outputs>
 </Outputs>
 <SymOutputs>
 </SymOutputs>
 <PathPredicate>
 </PathPredicate>
</TestCase>

=== ggranberry/acslyst/examples/TriType/testcases_TriType/Tritype/xml/TC_7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestCase SYSTEM "testcase.dtd">
<?xml-stylesheet href="testcase2html.xsl" type="text/xsl"?>
<TestCase TestCaseID="TC_7" PrevTestCaseID="TC_6" NextTestCaseID="TC_8" PrefixID="P_6">
 <SessionData>
  <FunName>Tritype</FunName>
  <Strategy Coverage="all-branches" IterLimit="none" RecurLimit="none" SuffixLengthLimit="none" />
  <When>Tue Jun 27 15:07:51 2023</When>
  <Version>4.0. Build Tue May  9 15:05:46 2023</Version>
  <TestReportFile>testreport.xml</TestReportFile>
  <TestSessionFile>testsession.xml</TestSessionFile>
 </SessionData>
 <Time>Tue Jun 27 15:07:52 2023</Time>
 <Dur>1</Dur>
 <Inputs>
  <VVal>
   <VName>i</VName>
   <Val>-0</Val>
  </VVal>
  <VVal>
   <VName>j</VName>
   <Val>4.9406564584124654e-324</Val>
  </VVal>
  <VVal>
   <VName>k</VName>
   <Val>-0</Val>
  </VVal>
 </Inputs>
 <Verdict Type="unknown" />
 <Prefix>
  <N BlocID="243" SrcFile="TriType.c">10a</N>
  <N BlocID="248">10b</N>
  <N BlocID="251">10c</N>
  <N BlocID="257">12a</N>
  <N BlocID="262">12b</N>
 </Prefix>
 <Suffix>
  <P BlocID="265" SrcFile="TriType.c">12c</P>
 </Suffix>
 <Outputs>
  <Output>
   <VName>return value</VName>
   <Val>3</Val>
  </Output>
 </Outputs>
 <SymOutputs>
  <SymOutput>
   <VName>return value</VName>
   <Val>3</Val>
  </SymOutput>
 </SymOutputs>
 <PathPredicate>
  <Ctr>i&gt;=0</Ctr>
  <Ctr>j&gt;=0</Ctr>
  <Ctr>k&gt;=0</Ctr>
  <Ctr>(i+j)&gt;k</Ctr>
  <Ctr>(j+k)&gt;i</Ctr>
  <Ctr>(k+i)=&lt;j</Ctr>
 </PathPredicate>
</TestCase>
