=== ggranberry/acslyst/examples/TriType/pathcrawler_TriType/testparams.dtd
<!--                                                                        -->
<!--                                                                        -->
<!--  This file is part of the Frama-C plug-in 'PathCrawler' (pc).          -->
<!--                                                                        -->
<!--  Copyright (C) 2007-2023                                               -->
<!--    CEA (Commissariat à l'énergie atomique et aux énergies              -->
<!--         alternatives)                                                  -->
<!--                                                                        -->
<!--  All rights reserved.                                                  -->
<!--  Contact CEA LIST for licensing.                                       -->
<!--                                                                        -->
<!--                                                                        -->

<!ELEMENT TestParams (FunTestParams*)>
<!ELEMENT FunTestParams (FunName,FunOffset?,(ArDom|VDom)*,UQPre*,QPre*,Strategy,CPre?)>
<!ELEMENT FunName (#PCDATA)>
<!ELEMENT FunOffset (#PCDATA)>
<!ELEMENT ArDom (VName,(Interval|Element)+)>
<!ATTLIST ArDom Type (int|float) #REQUIRED>
<!ELEMENT VDom (VName,(Interval|Element)+)>
<!ATTLIST VDom Type (int|float) #REQUIRED>
<!ELEMENT VName (ExpC,((ExpPIF,AuxPred*)|ErrMsg))>
<!ELEMENT Interval (ErrMsg?)>
<!ATTLIST Interval Left CDATA #REQUIRED
                   Right CDATA #REQUIRED>
<!ELEMENT Element (ErrMsg?)>
<!ATTLIST Element Number CDATA #REQUIRED>
<!ELEMENT Cond (Operand,Operand)>
<!ATTLIST Cond Operation (inf|infegal|sup|supegal|egal|diff) #REQUIRED>
<!ELEMENT Operand (ExpC,((ExpPIF,AuxPred*)|ErrMsg))>
<!ELEMENT ExpC (#PCDATA)>
<!ELEMENT ExpPIF (#PCDATA)>
<!ELEMENT AuxPred (#PCDATA)>
<!ELEMENT ErrMsg (#PCDATA)>
<!ELEMENT UQPre (Cond)>
<!ELEMENT QPre (UQVar+,Cond*,Operand,Operand)>
<!ATTLIST QPre Operation (inf|infegal|sup|supegal|egal|diff) #REQUIRED>
<!ELEMENT UQVar (ErrMsg?)>
<!ATTLIST UQVar Name CDATA #REQUIRED>
<!ELEMENT Strategy (ErrMsg?)>
<!ATTLIST Strategy IterNum CDATA #REQUIRED>
<!ELEMENT CPre EMPTY>
<!ATTLIST CPre PreFun CDATA #REQUIRED>
<!ATTLIST CPre Activate (yes|no) #REQUIRED>

=== ggranberry/acslyst/examples/TriType/pathcrawler_TriType/test_parameters.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TestParams SYSTEM "testparams.dtd">
<TestParams>
  <FunTestParams>
    <FunName>Tritype</FunName>
    <FunOffset>8956</FunOffset>
    <VDom Type="double">
      <VName>
        <ExpC>k</ExpC>
        <ExpPIF>&apos;k&apos;</ExpPIF>
      </VName>
      <Interval Left="-1.7976931348623157e+308" Right="1.7976931348623157e+308"/>
    </VDom>
    <VDom Type="double">
      <VName>
        <ExpC>j</ExpC>
        <ExpPIF>&apos;j&apos;</ExpPIF>
      </VName>
      <Interval Left="-1.7976931348623157e+308" Right="1.7976931348623157e+308"/>
    </VDom>
    <VDom Type="double">
      <VName>
        <ExpC>i</ExpC>
        <ExpPIF>&apos;i&apos;</ExpPIF>
      </VName>
      <Interval Left="-1.7976931348623157e+308" Right="1.7976931348623157e+308"/>
    </VDom>
    <Strategy/>
  </FunTestParams>
</TestParams>
